using System.Collections.Generic;
using Avalonia.Controls;

namespace WordLens.Infrastructure.Avalonia;

internal static class LocalizationResources
{
    public static void ApplyTo(ResourceDictionary dictionary, string culture)
    {
        dictionary.SetItems(CreateResourceItems(GetEntries(culture)));
    }

    private static IEnumerable<KeyValuePair<object, object?>> CreateResourceItems(
        IEnumerable<(string Key, string Value)> entries)
    {
        foreach (var (key, value) in entries)
            yield return new KeyValuePair<object, object?>(key, value);
    }

    private static (string Key, string Value)[] GetEntries(string culture)
    {
        return culture switch
        {
            "en" => En,
            "ja" => Ja,
            _ => ZhCn
        };
    }

    private static readonly (string Key, string Value)[] ZhCn =
    [
        ("App_SettingsTitle", "WordLens - 设置"),
        ("Common_Close", "关闭"),
        ("Common_Minimize", "最小化"),
        ("Common_PinTopmost", "置顶窗口"),
        ("Common_Copy", "复制"),
        ("Common_Clear", "清空"),
        ("Common_Translate", "翻译"),
        ("Common_Search", "搜索"),
        ("Common_Refresh", "刷新"),
        ("Common_Delete", "删除"),
        ("Common_Favorite", "收藏"),
        ("Common_Retranslate", "重新翻译"),
        ("Common_Reset", "重置"),
        ("Tray_ClipboardStart", "监听剪贴板"),
        ("Tray_ClipboardStop", "停止监听剪贴板"),
        ("Tray_Settings", "软件设置"),
        ("Tray_Exit", "退出程序"),
        ("Settings_Title", "设置"),
        ("Settings_General", "常规"),
        ("Settings_TranslationProviders", "翻译源"),
        ("Settings_Ocr", "OCR"),
        ("Settings_Tts", "TTS"),
        ("Settings_NetworkProxy", "网络代理"),
        ("Settings_History", "历史记录"),
        ("Settings_About", "关于"),
        ("Settings_AutoSaved", "已保存"),
        ("Settings_PendingSave", "待保存"),
        ("Settings_Saving", "保存中..."),
        ("Settings_SaveFailed", "保存失败"),
        ("Settings_LoadingRestoredSettings", "正在加载恢复的设置..."),
        ("Settings_Restored", "已恢复"),
        ("Settings_RestoreLoadFailed", "恢复后加载失败"),
        ("General_UILanguage_Title", "界面语言"),
        ("General_UILanguage_Description", "选择应用界面显示语言（翻译语言请在翻译窗口中选择）"),
        ("General_Font_Title", "界面字体"),
        ("General_Font_Placeholder", "输入字体名称"),
        ("General_Font_Description", "可选择系统字体，也可输入已安装字体名称；留空使用默认字体"),
        ("General_DefaultFontFormat", "默认字体 ({0})"),
        ("General_Startup_Title", "启动"),
        ("General_Startup_StartWithSystem", "开机时自动启动 WordLens"),
        ("General_Startup_Unsupported", "当前系统不支持自动配置开机自启"),
        ("General_Backup_Title", "数据备份"),
        ("General_Backup_Create", "备份数据"),
        ("General_Backup_Restore", "恢复备份"),
        ("General_Backup_Description", "备份包含设置、翻译历史数据库和截图缓存。恢复会覆盖当前数据，并自动创建一份恢复前备份。"),
        ("General_Backup_ChooseDestination", "请选择备份保存位置..."),
        ("General_Backup_Canceled", "已取消备份。"),
        ("General_Backup_Running", "正在创建备份..."),
        ("General_Backup_DoneFormat", "备份完成：{0} 个文件，{1}。"),
        ("General_Backup_FailedFormat", "备份失败：{0}"),
        ("General_Backup_SaveDialogTitle", "保存 WordLens 备份"),
        ("General_Restore_ChooseSource", "请选择要恢复的备份文件..."),
        ("General_Restore_Canceled", "已取消恢复。"),
        ("General_Restore_Running", "正在恢复备份..."),
        ("General_Restore_DoneFormat", "恢复完成：{0} 个文件。恢复前备份已保存为 {1}。"),
        ("General_Restore_FailedFormat", "恢复失败：{0}"),
        ("General_Restore_OpenDialogTitle", "选择 WordLens 备份"),
        ("General_LocalApi_Title", "本地 API"),
        ("General_LocalApi_Enable", "启用本地自动化 API"),
        ("General_LocalApi_Port", "监听端口"),
        ("General_LocalApi_Token", "访问 Token"),
        ("General_LocalApi_Description", "仅监听 127.0.0.1。外部调用需携带 Authorization: Bearer Token。"),
        ("General_Eudic_Title", "欧路生词本"),
        ("General_Eudic_Enable", "启用欧路词典生词本同步"),
        ("General_Eudic_Token", "OpenAPI Token"),
        ("General_Eudic_Language", "语言"),
        ("General_Eudic_CategoryId", "生词本 ID"),
        ("General_Eudic_Star", "星级"),
        ("General_Eudic_Description", "Token 可在欧路 OpenAPI 授权页生成；默认生词本 ID 通常为 0。"),
        ("General_PopupPosition_Title", "翻译框位置"),
        ("General_PopupPosition_Description", "跟随鼠标会在触发翻译时靠近当前鼠标位置；记住位置会使用上次关闭翻译框时的位置"),
        ("General_Hotkey_Title", "快捷键"),
        ("General_Hotkey_SetTranslation", "设置快捷键"),
        ("General_Hotkey_SetOcr", "设置OCR快捷键"),
        ("General_Hotkey_CapturePlaceholder", "请按下快捷键..."),
        ("General_Hotkey_CaptureHintActive", "请按下想要设置的快捷键组合（按 ESC 取消）"),
        ("General_Hotkey_CaptureHintIdle", "点击按钮后按下想要设置的快捷键组合"),
        ("General_Streaming_Title", "流式输出"),
        ("General_Streaming_Enable", "启用流式输出（实时显示翻译结果）"),
        ("General_Streaming_EnableTooltip", "启用后翻译内容将实时逐步显示，提供更好的用户体验"),
        ("General_Streaming_Delay", "打字机效果延迟（毫秒）"),
        ("General_Streaming_DelayTooltip", "每个字符显示之间的延迟时间"),
        ("General_Streaming_DelayDescription", "0 = 无延迟，实时显示；推荐值：30-50毫秒"),
        ("General_Streaming_Chars", "每次显示字符数"),
        ("General_Streaming_CharsTooltip", "一次性显示的字符数量"),
        ("General_Streaming_CharsDescription", "1 = 逐字显示；较大值可加快显示速度"),
        ("General_Streaming_Description", "提示：流式输出可以让翻译过程更加流畅，但如果网络不稳定可以关闭此功能"),
        ("General_Language_Chinese", "简体中文"),
        ("General_Language_English", "English"),
        ("General_Language_Japanese", "日本語"),
        ("General_EudicLanguage_English", "英语"),
        ("General_EudicLanguage_French", "法语"),
        ("General_EudicLanguage_German", "德语"),
        ("General_EudicLanguage_Spanish", "西语"),
        ("General_PopupPosition_FollowMouse", "跟随鼠标"),
        ("General_PopupPosition_RememberPosition", "记住位置"),
        ("Popup_WindowTitle", "WordLens - 翻译"),
        ("Popup_Title", "翻译"),
        ("Popup_SourceSection", "原文"),
        ("Popup_SourcePlaceholder", "输入或粘贴要翻译的文本"),
        ("Popup_CharacterCountFormat", "{0} 字符"),
        ("Popup_SpeakSource", "朗读原文"),
        ("Popup_CopySource", "复制原文"),
        ("Popup_AddVocabulary", "加入欧路生词本"),
        ("Popup_AddVocabularyRunning", "正在加入欧路生词本..."),
        ("Popup_ClearSource", "清空"),
        ("Popup_SwapLanguages", "交换语言"),
        ("Popup_ProviderLabel", "翻译源"),
        ("Popup_RetranslateWithProvider", "使用所选翻译源重新翻译"),
        ("Popup_RemoveResult", "移除此翻译源"),
        ("Popup_SpeakResult", "朗读此翻译"),
        ("Popup_CopyResult", "复制此翻译"),
        ("Popup_UseResultAsSource", "将译文作为新原文"),
        ("Popup_StatusLoading", "翻译中"),
        ("Popup_StatusDone", "完成"),
        ("Popup_StatusFailed", "失败"),
        ("Popup_ResizeTip", "拖拽调整窗口大小"),
        ("Ocr_WindowTitle", "WordLens - OCR"),
        ("Ocr_Title", "OCR 翻译"),
        ("Ocr_NoScreenshot", "暂无截图"),
        ("Ocr_EditorPlaceholder", "识别到的文字会显示在这里，也可以手动修正后再翻译"),
        ("Ocr_ReRecognize", "重新识别"),
        ("Ocr_StatusWaiting", "等待识别"),
        ("Ocr_StatusReady", "准备识别"),
        ("Ocr_StatusRecognizing", "正在识别..."),
        ("Ocr_StatusDoneFormat", "识别完成，{0} 个字符"),
        ("Ocr_StatusNoText", "未识别到文字"),
        ("Ocr_StatusFailedFormat", "识别失败：{0}"),
        ("History_Title", "翻译历史"),
        ("History_TotalCountFormat", "累计 {0} 条记录"),
        ("History_FilterFavorites", "仅收藏"),
        ("History_FilterAll", "全部"),
        ("History_FavoriteFilterTip", "收藏筛选"),
        ("History_ClearAllTip", "清空所有历史"),
        ("History_SearchPlaceholder", "搜索原文或翻译结果"),
        ("History_ResultLabel", "译文"),
        ("History_EmptyTitle", "暂无翻译历史"),
        ("History_EmptyDescription", "翻译完成后会显示在这里"),
        ("History_LoadMore", "加载更多"),
    ];

    private static readonly (string Key, string Value)[] En =
    [
        ("App_SettingsTitle", "WordLens - Settings"),
        ("Common_Close", "Close"),
        ("Common_Minimize", "Minimize"),
        ("Common_PinTopmost", "Keep on top"),
        ("Common_Copy", "Copy"),
        ("Common_Clear", "Clear"),
        ("Common_Translate", "Translate"),
        ("Common_Search", "Search"),
        ("Common_Refresh", "Refresh"),
        ("Common_Delete", "Delete"),
        ("Common_Favorite", "Favorite"),
        ("Common_Retranslate", "Translate again"),
        ("Common_Reset", "Reset"),
        ("Tray_ClipboardStart", "Monitor clipboard"),
        ("Tray_ClipboardStop", "Stop clipboard monitor"),
        ("Tray_Settings", "Settings"),
        ("Tray_Exit", "Exit"),
        ("Settings_Title", "Settings"),
        ("Settings_General", "General"),
        ("Settings_TranslationProviders", "Translation"),
        ("Settings_Ocr", "OCR"),
        ("Settings_Tts", "TTS"),
        ("Settings_NetworkProxy", "Network"),
        ("Settings_History", "History"),
        ("Settings_About", "About"),
        ("Settings_AutoSaved", "Saved"),
        ("Settings_PendingSave", "Pending save"),
        ("Settings_Saving", "Saving..."),
        ("Settings_SaveFailed", "Save failed"),
        ("Settings_LoadingRestoredSettings", "Loading restored settings..."),
        ("Settings_Restored", "Restored"),
        ("Settings_RestoreLoadFailed", "Failed to load restored settings"),
        ("General_UILanguage_Title", "Interface language"),
        ("General_UILanguage_Description", "Choose the app interface language. Translation languages are selected in the translation window."),
        ("General_Font_Title", "Interface font"),
        ("General_Font_Placeholder", "Enter font family"),
        ("General_Font_Description", "Choose a system font or enter an installed font name. Leave empty to use the default font."),
        ("General_DefaultFontFormat", "Default font ({0})"),
        ("General_Startup_Title", "Startup"),
        ("General_Startup_StartWithSystem", "Start WordLens when the system starts"),
        ("General_Startup_Unsupported", "This system does not support automatic startup configuration."),
        ("General_Backup_Title", "Data backup"),
        ("General_Backup_Create", "Back up data"),
        ("General_Backup_Restore", "Restore backup"),
        ("General_Backup_Description", "Backups include settings, translation history, and screenshot cache. Restore overwrites current data and creates a pre-restore backup."),
        ("General_Backup_ChooseDestination", "Choose where to save the backup..."),
        ("General_Backup_Canceled", "Backup canceled."),
        ("General_Backup_Running", "Creating backup..."),
        ("General_Backup_DoneFormat", "Backup complete: {0} files, {1}."),
        ("General_Backup_FailedFormat", "Backup failed: {0}"),
        ("General_Backup_SaveDialogTitle", "Save WordLens backup"),
        ("General_Restore_ChooseSource", "Choose a backup file to restore..."),
        ("General_Restore_Canceled", "Restore canceled."),
        ("General_Restore_Running", "Restoring backup..."),
        ("General_Restore_DoneFormat", "Restore complete: {0} files. Pre-restore backup saved as {1}."),
        ("General_Restore_FailedFormat", "Restore failed: {0}"),
        ("General_Restore_OpenDialogTitle", "Choose WordLens backup"),
        ("General_LocalApi_Title", "Local API"),
        ("General_LocalApi_Enable", "Enable local automation API"),
        ("General_LocalApi_Port", "Port"),
        ("General_LocalApi_Token", "Access token"),
        ("General_LocalApi_Description", "Listens only on 127.0.0.1. External calls must include Authorization: Bearer Token."),
        ("General_Eudic_Title", "Eudic vocabulary"),
        ("General_Eudic_Enable", "Sync to Eudic vocabulary book"),
        ("General_Eudic_Token", "OpenAPI token"),
        ("General_Eudic_Language", "Language"),
        ("General_Eudic_CategoryId", "Book ID"),
        ("General_Eudic_Star", "Star level"),
        ("General_Eudic_Description", "Generate the token from the Eudic OpenAPI authorization page. The default book ID is usually 0."),
        ("General_PopupPosition_Title", "Translation window position"),
        ("General_PopupPosition_Description", "Follow mouse places the window near the cursor. Remember position uses the last position when the window was closed."),
        ("General_Hotkey_Title", "Hotkeys"),
        ("General_Hotkey_SetTranslation", "Set hotkey"),
        ("General_Hotkey_SetOcr", "Set OCR hotkey"),
        ("General_Hotkey_CapturePlaceholder", "Press a hotkey..."),
        ("General_Hotkey_CaptureHintActive", "Press the hotkey combination to use. Press Esc to cancel."),
        ("General_Hotkey_CaptureHintIdle", "Click a button, then press the hotkey combination."),
        ("General_Streaming_Title", "Streaming output"),
        ("General_Streaming_Enable", "Enable streaming output"),
        ("General_Streaming_EnableTooltip", "Shows translation content progressively in real time."),
        ("General_Streaming_Delay", "Typewriter delay (ms)"),
        ("General_Streaming_DelayTooltip", "Delay between displayed characters."),
        ("General_Streaming_DelayDescription", "0 = no delay. Recommended: 30-50 ms."),
        ("General_Streaming_Chars", "Characters per update"),
        ("General_Streaming_CharsTooltip", "Number of characters displayed per update."),
        ("General_Streaming_CharsDescription", "1 = character by character. Higher values display faster."),
        ("General_Streaming_Description", "Streaming makes translation feel smoother. Disable it if the network is unstable."),
        ("General_Language_Chinese", "简体中文"),
        ("General_Language_English", "English"),
        ("General_Language_Japanese", "日本語"),
        ("General_EudicLanguage_English", "English"),
        ("General_EudicLanguage_French", "French"),
        ("General_EudicLanguage_German", "German"),
        ("General_EudicLanguage_Spanish", "Spanish"),
        ("General_PopupPosition_FollowMouse", "Follow mouse"),
        ("General_PopupPosition_RememberPosition", "Remember position"),
        ("Popup_WindowTitle", "WordLens - Translate"),
        ("Popup_Title", "Translate"),
        ("Popup_SourceSection", "Source"),
        ("Popup_SourcePlaceholder", "Enter or paste text to translate"),
        ("Popup_CharacterCountFormat", "{0} chars"),
        ("Popup_SpeakSource", "Read source text"),
        ("Popup_CopySource", "Copy source text"),
        ("Popup_AddVocabulary", "Add to Eudic vocabulary"),
        ("Popup_AddVocabularyRunning", "Adding to Eudic vocabulary..."),
        ("Popup_ClearSource", "Clear"),
        ("Popup_SwapLanguages", "Swap languages"),
        ("Popup_ProviderLabel", "Provider"),
        ("Popup_RetranslateWithProvider", "Translate again with the selected provider"),
        ("Popup_RemoveResult", "Remove this provider result"),
        ("Popup_SpeakResult", "Read this translation"),
        ("Popup_CopyResult", "Copy this translation"),
        ("Popup_UseResultAsSource", "Use translation as new source"),
        ("Popup_StatusLoading", "Translating"),
        ("Popup_StatusDone", "Done"),
        ("Popup_StatusFailed", "Failed"),
        ("Popup_ResizeTip", "Drag to resize"),
        ("Ocr_WindowTitle", "WordLens - OCR"),
        ("Ocr_Title", "OCR translate"),
        ("Ocr_NoScreenshot", "No screenshot"),
        ("Ocr_EditorPlaceholder", "Recognized text appears here. You can edit it before translating."),
        ("Ocr_ReRecognize", "Recognize again"),
        ("Ocr_StatusWaiting", "Waiting for recognition"),
        ("Ocr_StatusReady", "Ready to recognize"),
        ("Ocr_StatusRecognizing", "Recognizing..."),
        ("Ocr_StatusDoneFormat", "Recognition complete, {0} chars"),
        ("Ocr_StatusNoText", "No text recognized"),
        ("Ocr_StatusFailedFormat", "Recognition failed: {0}"),
        ("History_Title", "Translation history"),
        ("History_TotalCountFormat", "{0} records total"),
        ("History_FilterFavorites", "Favorites"),
        ("History_FilterAll", "All"),
        ("History_FavoriteFilterTip", "Favorite filter"),
        ("History_ClearAllTip", "Clear all history"),
        ("History_SearchPlaceholder", "Search source or translation"),
        ("History_ResultLabel", "Translation"),
        ("History_EmptyTitle", "No translation history"),
        ("History_EmptyDescription", "Completed translations will appear here."),
        ("History_LoadMore", "Load more"),
    ];

    private static readonly (string Key, string Value)[] Ja =
    [
        ("App_SettingsTitle", "WordLens - 設定"),
        ("Common_Close", "閉じる"),
        ("Common_Minimize", "最小化"),
        ("Common_PinTopmost", "最前面に固定"),
        ("Common_Copy", "コピー"),
        ("Common_Clear", "クリア"),
        ("Common_Translate", "翻訳"),
        ("Common_Search", "検索"),
        ("Common_Refresh", "更新"),
        ("Common_Delete", "削除"),
        ("Common_Favorite", "お気に入り"),
        ("Common_Retranslate", "再翻訳"),
        ("Common_Reset", "リセット"),
        ("Tray_ClipboardStart", "クリップボードを監視"),
        ("Tray_ClipboardStop", "監視を停止"),
        ("Tray_Settings", "設定"),
        ("Tray_Exit", "終了"),
        ("Settings_Title", "設定"),
        ("Settings_General", "一般"),
        ("Settings_TranslationProviders", "翻訳"),
        ("Settings_Ocr", "OCR"),
        ("Settings_Tts", "TTS"),
        ("Settings_NetworkProxy", "ネットワーク"),
        ("Settings_History", "履歴"),
        ("Settings_About", "情報"),
        ("Settings_AutoSaved", "保存済み"),
        ("Settings_PendingSave", "保存待ち"),
        ("Settings_Saving", "保存中..."),
        ("Settings_SaveFailed", "保存に失敗しました"),
        ("Settings_LoadingRestoredSettings", "復元した設定を読み込み中..."),
        ("Settings_Restored", "復元済み"),
        ("Settings_RestoreLoadFailed", "復元後の設定読み込みに失敗しました"),
        ("General_UILanguage_Title", "表示言語"),
        ("General_UILanguage_Description", "アプリの表示言語を選択します。翻訳言語は翻訳ウィンドウで選択します。"),
        ("General_Font_Title", "表示フォント"),
        ("General_Font_Placeholder", "フォント名を入力"),
        ("General_Font_Description", "システムフォントを選択するか、インストール済みフォント名を入力します。空欄の場合は既定フォントを使用します。"),
        ("General_DefaultFontFormat", "既定フォント ({0})"),
        ("General_Startup_Title", "起動"),
        ("General_Startup_StartWithSystem", "システム起動時に WordLens を起動"),
        ("General_Startup_Unsupported", "このシステムでは自動起動設定に対応していません。"),
        ("General_Backup_Title", "データバックアップ"),
        ("General_Backup_Create", "バックアップ"),
        ("General_Backup_Restore", "復元"),
        ("General_Backup_Description", "バックアップには設定、翻訳履歴、スクリーンショットキャッシュが含まれます。復元すると現在のデータが上書きされ、復元前バックアップが作成されます。"),
        ("General_Backup_ChooseDestination", "バックアップの保存先を選択してください..."),
        ("General_Backup_Canceled", "バックアップをキャンセルしました。"),
        ("General_Backup_Running", "バックアップを作成中..."),
        ("General_Backup_DoneFormat", "バックアップ完了：{0} ファイル、{1}。"),
        ("General_Backup_FailedFormat", "バックアップ失敗：{0}"),
        ("General_Backup_SaveDialogTitle", "WordLens バックアップを保存"),
        ("General_Restore_ChooseSource", "復元するバックアップファイルを選択してください..."),
        ("General_Restore_Canceled", "復元をキャンセルしました。"),
        ("General_Restore_Running", "復元中..."),
        ("General_Restore_DoneFormat", "復元完了：{0} ファイル。復元前バックアップは {1} として保存されました。"),
        ("General_Restore_FailedFormat", "復元失敗：{0}"),
        ("General_Restore_OpenDialogTitle", "WordLens バックアップを選択"),
        ("General_LocalApi_Title", "ローカル API"),
        ("General_LocalApi_Enable", "ローカル自動化 API を有効化"),
        ("General_LocalApi_Port", "待受ポート"),
        ("General_LocalApi_Token", "アクセストークン"),
        ("General_LocalApi_Description", "127.0.0.1 のみで待ち受けます。外部呼び出しには Authorization: Bearer Token が必要です。"),
        ("General_Eudic_Title", "Eudic 単語帳"),
        ("General_Eudic_Enable", "Eudic 単語帳同期を有効化"),
        ("General_Eudic_Token", "OpenAPI トークン"),
        ("General_Eudic_Language", "言語"),
        ("General_Eudic_CategoryId", "単語帳 ID"),
        ("General_Eudic_Star", "星レベル"),
        ("General_Eudic_Description", "トークンは Eudic OpenAPI 認可ページで生成できます。既定の単語帳 ID は通常 0 です。"),
        ("General_PopupPosition_Title", "翻訳ウィンドウ位置"),
        ("General_PopupPosition_Description", "マウス追従はカーソル付近に表示します。位置を記憶すると前回閉じた位置を使用します。"),
        ("General_Hotkey_Title", "ホットキー"),
        ("General_Hotkey_SetTranslation", "ホットキー設定"),
        ("General_Hotkey_SetOcr", "OCR ホットキー設定"),
        ("General_Hotkey_CapturePlaceholder", "ホットキーを押してください..."),
        ("General_Hotkey_CaptureHintActive", "使用するキー組み合わせを押してください。Esc でキャンセルします。"),
        ("General_Hotkey_CaptureHintIdle", "ボタンをクリックしてからキー組み合わせを押してください。"),
        ("General_Streaming_Title", "ストリーミング出力"),
        ("General_Streaming_Enable", "ストリーミング出力を有効化"),
        ("General_Streaming_EnableTooltip", "翻訳結果をリアルタイムで段階的に表示します。"),
        ("General_Streaming_Delay", "タイプライター遅延 (ms)"),
        ("General_Streaming_DelayTooltip", "文字表示間の遅延時間。"),
        ("General_Streaming_DelayDescription", "0 = 遅延なし。推奨値：30-50 ms。"),
        ("General_Streaming_Chars", "一度に表示する文字数"),
        ("General_Streaming_CharsTooltip", "更新ごとに表示する文字数。"),
        ("General_Streaming_CharsDescription", "1 = 一文字ずつ表示。大きい値ほど高速です。"),
        ("General_Streaming_Description", "ストリーミングにより翻訳表示が滑らかになります。ネットワークが不安定な場合は無効にできます。"),
        ("General_Language_Chinese", "简体中文"),
        ("General_Language_English", "English"),
        ("General_Language_Japanese", "日本語"),
        ("General_EudicLanguage_English", "英語"),
        ("General_EudicLanguage_French", "フランス語"),
        ("General_EudicLanguage_German", "ドイツ語"),
        ("General_EudicLanguage_Spanish", "スペイン語"),
        ("General_PopupPosition_FollowMouse", "マウスに追従"),
        ("General_PopupPosition_RememberPosition", "位置を記憶"),
        ("Popup_WindowTitle", "WordLens - 翻訳"),
        ("Popup_Title", "翻訳"),
        ("Popup_SourceSection", "原文"),
        ("Popup_SourcePlaceholder", "翻訳するテキストを入力または貼り付け"),
        ("Popup_CharacterCountFormat", "{0} 文字"),
        ("Popup_SpeakSource", "原文を読み上げ"),
        ("Popup_CopySource", "原文をコピー"),
        ("Popup_AddVocabulary", "Eudic 単語帳に追加"),
        ("Popup_AddVocabularyRunning", "Eudic 単語帳に追加中..."),
        ("Popup_ClearSource", "クリア"),
        ("Popup_SwapLanguages", "言語を入れ替え"),
        ("Popup_ProviderLabel", "翻訳元"),
        ("Popup_RetranslateWithProvider", "選択した翻訳元で再翻訳"),
        ("Popup_RemoveResult", "この翻訳元を削除"),
        ("Popup_SpeakResult", "この翻訳を読み上げ"),
        ("Popup_CopyResult", "この翻訳をコピー"),
        ("Popup_UseResultAsSource", "翻訳を新しい原文として使用"),
        ("Popup_StatusLoading", "翻訳中"),
        ("Popup_StatusDone", "完了"),
        ("Popup_StatusFailed", "失敗"),
        ("Popup_ResizeTip", "ドラッグしてサイズ変更"),
        ("Ocr_WindowTitle", "WordLens - OCR"),
        ("Ocr_Title", "OCR 翻訳"),
        ("Ocr_NoScreenshot", "スクリーンショットなし"),
        ("Ocr_EditorPlaceholder", "認識した文字がここに表示されます。翻訳前に修正できます。"),
        ("Ocr_ReRecognize", "再認識"),
        ("Ocr_StatusWaiting", "認識待ち"),
        ("Ocr_StatusReady", "認識準備完了"),
        ("Ocr_StatusRecognizing", "認識中..."),
        ("Ocr_StatusDoneFormat", "認識完了、{0} 文字"),
        ("Ocr_StatusNoText", "文字を認識できませんでした"),
        ("Ocr_StatusFailedFormat", "認識失敗：{0}"),
        ("History_Title", "翻訳履歴"),
        ("History_TotalCountFormat", "合計 {0} 件"),
        ("History_FilterFavorites", "お気に入り"),
        ("History_FilterAll", "すべて"),
        ("History_FavoriteFilterTip", "お気に入りフィルター"),
        ("History_ClearAllTip", "すべての履歴をクリア"),
        ("History_SearchPlaceholder", "原文または翻訳結果を検索"),
        ("History_ResultLabel", "訳文"),
        ("History_EmptyTitle", "翻訳履歴はありません"),
        ("History_EmptyDescription", "翻訳が完了するとここに表示されます。"),
        ("History_LoadMore", "さらに読み込む"),
    ];
}
