<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net11.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
        <TargetFrameworks>$(TargetFrameworks);net11.0-macos</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0-macos'">
        <SupportedOSPlatformVersion>14.0</SupportedOSPlatformVersion>
        <DefineConstants>$(DefineConstants);MACOS</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WordLens.Abstractions\WordLens.Abstractions.csproj" />
    </ItemGroup>

</Project>
